version: '3.8'

services:
  ### MYSQL DATABASE ###
  mysql:
    image: mysql:8.0
    container_name: webroster-adms-server-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webroster-adms-server

  ### PHP & LARAVEL ###
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webroster-adms-server-app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - webroster-adms-server
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password

  ### NGINX WEB SERVER ###
  web:
    image: nginx:alpine
    container_name: webroster-adms-server-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - webroster-adms-server

  ### PHPMYADMIN ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webroster-adms-server-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
    networks:
      - webroster-adms-server

networks:
  webroster-adms-server:

volumes:
  mysql_data:
